config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/categorias/:id' => 'clients#show'
  get '/contacto' => 'clients#contacto'
  get '/menu' => 'clients#menu'

  get '/ventas' => 'sales#index'

  resources :menus
  resources :categories
  resources :dishes
  resources :drinks
  resources :orders
  resources :foods

  root 'clients#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  #Paperclip attached images
  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  #Relations
  belongs_to :menu

  has_many :dishes
  has_many :drinks

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :orders
  has_one :seat

end

app/models/dish.rb
class Dish < ActiveRecord::Base

  #Paperclip attached images
  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  #Relations
  belongs_to :category

  has_many :ingridients

end

app/models/drink.rb
class Drink < ActiveRecord::Base

    #Paperclip attached images
    has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

    #Relations
    belongs_to :category

    has_many :ingridients

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :seats
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :order
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :dish
  belongs_to :drink
end

app/models/menu.rb
class Menu < ActiveRecord::Base

  has_many :categories

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :foods

  belongs_to :clients

end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :employee
  belongs_to :client

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  before_action :set_menu, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @menus = Menu.all
  end

  def show
  end

  def new
    @menu = Menu.new
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
      @categories = @menu.categories
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name, :isDefault)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/din_helper.rb
module DinHelper
end

app/helpers/dish_helper.rb
module DishHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/drink_helper.rb
module DrinkHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-backend">
    <%= f.label :Nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field-backend">
    <%= f.label :Menu_Por_Defecto %><br>
    <%= f.check_box :isDefault %>
  </div>

  <div class="actions-backend">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<%= render '/orders/header' %>
<%= render 'form' %>
<%= link_to 'Show', @menu %>
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<%= render '/orders/header' %>
<div class="mainBox-backend">
  <section>
    <div class="title-backend">
      <h1>Showing the menus database</h1>
    </div>
    <div class="subtitle-backend">
      <p>In this section you can check and have acces to the menus</p>
    </div>
  </section>
  <section class="article-backend">
    <div class="articlehead-backend">
      <h2>Listing al Menus</h1>
      </div>
    </div>
    <div class="list-backend">
      <table>
        <thead>
          <tr>
            <td>ID</td>
            <td>Name</td>
          </tr>
        </thead>
        <tbody>
          <% @menus.each do |menu| %>
          <tr>
            <td><%= menu.id %></td>
            <td><%= menu.name %></td>
            <td><%= link_to 'Show', menu %></td>
            <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
            <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Nuevo menu', new_menu_path() %>
    </div>
  </section>
</div>

app/views/menus/new.html.erb
<%= render '/orders/header' %>
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<%= render '/orders/header' %>
<p>
  <strong>ID:</strong>
  <%= @menu.id %>
</p>
<p>
  <strong>Nombre:</strong>
  <%= @menu.name %>
</p>
<p>
  <strong>Menu por defecto:</strong>
  <%= @menu.isDefault %>
</p>

<div clas="list-backend">
  <table>
    <thead>
      <tr>
        <td>ID</td>
        <td>Name</td>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= image_tag category.photo.url(:thumb) %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Nueva categoria', new_category_path() %>
</div>

<%= link_to 'Edit', edit_menu_path(@menu) %>
<%= link_to 'Back', menus_path %>