config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/categorias/:id' => 'clients#show'
  get '/contacto' => 'clients#contacto'
  get '/menu' => 'clients#menu'

  get '/ventas' => 'sales#index'

  resources :menus
  resources :categories
  resources :dishes
  resources :drinks
  resources :orders
  resources :foods

  root 'clients#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  #Paperclip attached images
  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  #Relations
  belongs_to :menu

  has_many :dishes
  has_many :drinks

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :orders
  has_one :seat

end

app/models/dish.rb
class Dish < ActiveRecord::Base

  #Paperclip attached images
  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  #Relations
  belongs_to :category

  has_many :ingridients

end

app/models/drink.rb
class Drink < ActiveRecord::Base

    #Paperclip attached images
    has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

    #Relations
    belongs_to :category

    has_many :ingridients

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :seats
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :order
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :dish
  belongs_to :drink
end

app/models/menu.rb
class Menu < ActiveRecord::Base

  has_many :categories

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :foods

  belongs_to :clients

end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :employee
  belongs_to :client

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

  before_action :set_drink, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit, :destroy, :update]
  before_action :authenticate_user!

  def index
    @drinks = Drink.all
  end

  def show
  end

  def new
    @drink = Drink.new
  end

  def edit
  end

  def create
    @drink = Drink.new(drink_params)

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render :show, status: :created, location: @drink }
      else
        format.html { render :new }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @drink.update(drink_params)
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink }
      else
        format.html { render :edit }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @drink.destroy
    respond_to do |format|
      format.html { redirect_to drinks_url, notice: 'Drink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drink
      @drink = Drink.find(params[:id])
    end

    def set_categories
      @categories = Array.new

      Category.all.each do |c|
        @categories.push(c.id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drink_params
      params.require(:drink).permit(:name, :price, :description, :photo, :category_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/din_helper.rb
module DinHelper
end

app/helpers/dish_helper.rb
module DishHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/drink_helper.rb
module DrinkHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/drinks/_form.html.erb
<%= form_for @drink, html: { multipart: true } do |f| %>
  <% if @drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drink.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @drink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-backend">
    <%= f.label :Nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field-backend">
    <%= f.label :Precio %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field-backend">
    <%= f.label :Descripcion %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field-backend">
    <%= f.label :Imagen %>
    <%= f.file_field :photo %>
  </div>
  <div class="field-backend">
    <%= f.label :Pertenece_a %>
    <%= f.select(:category_id, options_for_select(@categories)) %>
  </div>

  <div class="actions-backend">
    <%= f.submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<%= render '/orders/header' %>
<%= render 'form' %>
<%= link_to 'Show', @drink %>
<%= link_to 'Back', drinks_path %>

app/views/drinks/index.html.erb
drink<%= render '/orders/header' %>
<div class="mainBox-backend">
  <section>
    <div class="title-backend">
      <h1>Showing the Drinks database</h1>
    </div>
    <div class="subtitle-backend">
      <p>In this section you can check and have acces to the Drinks</p>
    </div>
  </section>
  <section class="article-backend">
    <div class="articlehead-backend">
      <h2>Listing al Drinks</h1>
      </div>
    </div>
    <div class="list-backend">
      <table>
        <thead>
          <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Precio</td>
          </tr>
        </thead>
        <tbody>
          <% @drinks.each do |drink| %>
          <tr>
            <td><%= drink.id %></td>
            <td><%= drink.name %></td>
            <td><%= drink.price %></td>
            <td><%= link_to 'Show', drink %></td>
            <td><%= link_to 'Edit', edit_drink_path(drink) %></td>
            <td><%= link_to 'Destroy', drink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Nueva bebida', new_drink_path() %>
    </div>
  </section>
</div>

app/views/drinks/new.html.erb
<%= render '/orders/header' %>
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', drinks_path %>

app/views/drinks/show.html.erb
<%= render '/orders/header' %>
<p>
  <strong>ID:</strong>
  <%= @drink.id %>
</p>
<p>
  <strong>Nombre:</strong>
  <%= @drink.name %>
</p>

<!-- Mostrando bebidas !-->
<div clas="list-backend">
  <table>
    <thead>
      <tr>
        <td>ID</td>
        <td>Name</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @drink.id %></td>
        <td><%= @drink.name %></td>
        <td><%= link_to 'Edit', edit_drink_path(@drink) %></td>
        <td><%= link_to 'Destroy', @drink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'Back', drinks_path %>