config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/categorias/:id' => 'clients#show'
  get '/contacto' => 'clients#contacto'
  get '/menu' => 'clients#menu'

  get '/ventas' => 'sales#index'

  resources :menus
  resources :categories
  resources :dishes
  resources :drinks
  resources :orders
  resources :foods

  root 'clients#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  #Paperclip attached images
  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  #Relations
  belongs_to :menu

  has_many :dishes
  has_many :drinks

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :orders
  has_one :seat

end

app/models/dish.rb
class Dish < ActiveRecord::Base

  #Paperclip attached images
  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  #Relations
  belongs_to :category

  has_many :ingridients

end

app/models/drink.rb
class Drink < ActiveRecord::Base

    #Paperclip attached images
    has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

    #Relations
    belongs_to :category

    has_many :ingridients

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :seats
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :order
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :dish
  belongs_to :drink
end

app/models/menu.rb
class Menu < ActiveRecord::Base

  has_many :categories

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :foods

  belongs_to :clients

end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :employee
  belongs_to :client

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_menus, only: [:new, :edit, :destroy, :update]
  before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      @dishes = @category.dishes
      @drinks = @category.drinks
    end

    def set_menus
      @menus = Array.new

      Menu.all.each do |m|
        @menus.push(m.id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :photo, :menu_id)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/din_helper.rb
module DinHelper
end

app/helpers/dish_helper.rb
module DishHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/drink_helper.rb
module DrinkHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/categories/_form.html.erb
<div class="mainBox-backend">
  <%= form_for @category, html: { multipart: true } do |f| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this menu from being saved:</h2>

        <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field-backend">
      <%= f.label :Nombre %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field-backend">
      <%= f.label :Descripcion %>
      <%= f.text_area :description %>
    </div>
    <div class="field-backend">
      <%= f.label :Imagen %>
      <%= f.file_field :photo %>
    </div>
    <div class="field-backend">
      <%= f.label :Pertenece_a %>
      <%= f.select(:menu_id, options_for_select(@menus)) %>
    </div>

    <div class="actions-backend">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/categories/_restricted.html.erb
<section class="noSession-backend">
  <div class="title-backend">
    <h1>Como llegaste aqui?</h1>
    <p>
      Solo sesiones oficiales
    </p>
  </div>
  <div class="info-backend">
    Esta seccion es solo para personal autorizado, si llegaste aqui desde la aplicacion poara ordenar por favor deja informacion
    sobre el error en la seccion de "feedback".
  </div>
</section>

app/views/categories/edit.html.erb
<%= render '/orders/header' %>
<%= render 'form' %>
<%= link_to 'Show', @category %>
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= render '/orders/header' %>
<div class="mainBox-backend">
  <section>
    <div class="title-backend">
      <h1>Showing the categories database</h1>
    </div>
    <div class="subtitle-backend">
      <p>In this section you can check and have acces to the categories</p>
    </div>
  </section>
  <section class="article-backend">
    <div class="articlehead-backend">
      <h2>Listing al Categories</h1>
      </div>
    </div>
    <div clas="list-backend">
      <table>
        <thead>
          <tr>
            <td>ID</td>
            <td>Name</td>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <td><%= category.id %></td>
            <td><%= category.name %></td>
            <td><%= link_to 'Show', category %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Nueva categoria', new_category_path() %>
    </div>
  </section>
</div>

app/views/categories/new.html.erb
<%= render '/orders/header' %>
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= render '/orders/header' %>
<p>
  <strong>ID:</strong>
  <%= @category.id %>
</p>
<p>
  <strong>Nombre:</strong>
  <%= @category.name %>
</p>

<!-- Mostrando platillos !-->
<div clas="list-backend">
  <table>
    <thead>
      <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Precio</td>
      </tr>
    </thead>
    <tbody>
      <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.id %></td>
        <td><%= dish.name %></td>
        <td>$<%= dish.price%></td>
        <td><%= image_tag dish.photo.url(:thumb) %></td>
        <td><%= link_to 'Show', dish %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Nuevo platillo', new_dish_path() %>
</div>

<!-- Mostrando bebidas !-->
<div clas="list-backend">
  <table>
    <thead>
      <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Precio</td>
      </tr>
    </thead>
    <tbody>
      <% @drinks.each do |drink| %>
      <tr>
        <td><%= drink.id %></td>
        <td><%= drink.name %></td>
        <td>$<%= drink.price%></td>
        <td><%= image_tag drink.photo.url(:thumb) %></td>
        <td><%= link_to 'Show', drink %></td>
        <td><%= link_to 'Edit', edit_drink_path(drink) %></td>
        <td><%= link_to 'Destroy', drink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Nueva bebida', new_drink_path() %>
</div>

<%= link_to 'Edit', edit_category_path(@category) %>
<%= link_to 'Back', categories_path %>